global:
  # how often to check the status
  scrape_interval: 5s
scrape_configs:
  - job_name: 'sentinel monitor'
    static_configs:
      # redirecting the target of prometheus to our local machine's(in this case docker) port
      - targets: ['host.docker.internal:8000']
